version: '3.7'
services:
  jenkins:
    image: 'jenkins/jenkins:lts'
    container_name: jenkins
    ports:
      - '8080:8080'
      - '8443:8443'
      - '50000:50000'
    environment:
      #- ''
      #- 'JENKINS_USERNAME=admin'
      #- 'JENKINS_PASSWORD=admin'
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
volumes:
  jenkins_data: